version: '2'
services:
  expo:
    image: yosmy/expo
    container_name: mundorecarga_app_expo
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
    volumes:
      - ../:/app
      - ./entrypoint.sh:/entrypoint.sh
    networks:
      - frontend
    working_dir: /app
    entrypoint: /entrypoint.sh

networks:
  frontend:
    external: true
